# Generated by Django 3.0.5 on 2021-09-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'verbose_name': 'メモ', 'verbose_name_plural': 'メモ'},
        ),
    ]
